### ISSUE TITLE
Add link for youtube video series to ReadMe - hacktoberfest

### ISSUE THREAD

**Issue by tthompson899** [tthompson899/appointment#13]
Add a section for ReadMe that shows a link to the video playlist series from YouTube

Example - Add after About Appointment section and before Tech stack section:

## Video Series Link  ##
If you would like to follow along in the series - The playlist link for this video series can be found here: https://youtube.com/playlist?list=PLxyLoVOL_gY5SzhYeWqDkKHxxl8hETqQb

**Comment by Nikhil-1503** [comment]
Can I work on this?

**Comment by mingweisoo** [comment]
I am willing to work on this, please assign it to me.

**Comment by tthompson899** [comment]
Looks like a PR is open for it. Thanks for your interest.

**Comment by tthompson899** [comment]
This issue is closed by PR #17
