### ISSUE TITLE
Add testing notes to ReadMe

### ISSUE THREAD

**Issue by tthompson899** [tthompson899/appointment#18]
In the readme file, after the How to Setup and before the How to view api section - Add the testing section. 
I have included the format for the testing section below: 

## How to run Test ##
To run initial database seeder: `php artisan db:seed`
To remove tables and add new data: `php artisan migrate:fresh --seed`
If you make changes run the command again (php artisan db:seed) to confirm changes in database

**Comment by LuluNwenyi** [comment]
Hi @tthompson899, can I be assigned to this? I’d love to work on it

**Comment by tthompson899** [comment]
Hey @LuluNwenyi Yes, go for it 😃

**Comment by LuluNwenyi** [comment]
Hi @tthompson899, I've opened PR #19 for this issue. Please let me know if there's any other thing you'd like me to add to it.

**Comment by tthompson899** [comment]
@LuluNwenyi Awesome! I'll take a look within the next couple days and get back with you.
